# Создание и заполнение данных БД Postgre

In [2]:
%pip install python-dotenv sqlalchemy psycopg2-binary pandas ipython-sql

Requirement already satisfied: python-dotenv in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (1.2.2)
Requirement already satisfied: sqlalchemy in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (2.9.11)
Requirement already satisfied: pandas in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (3.0.1)
Collecting ipython-sql
  Downloading ipython_sql-0.5.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: greenlet>=1 in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from pandas) (2025.3)
Collecting prettytable (from ipython-sql)
  Downloading prettytable-3.17.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: ipython in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from ipython-sql) (9.11.0)
Collecting sqlparse (from ipython-sql)
  Downloading sqlparse-0.5.5-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: six in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from ipython-sql) (1.17.0)
Collecting ipython-genutils (from ipython-sql)
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl.metadata (755 bytes)
Requirement already satisfied: colorama>=0.4.4 in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from ipython->ipython-sql) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from ipython->ipython-sql) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.6 in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from ipython->ipython-sql) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from ipython->ipython-sql) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: wcwidth in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from jedi>=0.18.2->ipython->ipython-sql) (0.8.6)
Requirement already satisfied: executing>=1.2.0 in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (3.0.1)
Requirement already satisfied: pure-eval in c:\users\skyreed\datagripprojects\labs\.venv\lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (0.2.3)
Downloading ipython_sql-0.5.0-py3-none-any.whl (20 kB)
Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Downloading prettytable-3.17.0-py3-none-any.whl (34 kB)
Downloading sqlparse-0.5.5-py3-none-any.whl (46 kB)
Installing collected packages: ipython-genutils, sqlparse, prettytable, ipython-sql

   -------------------- ------------------- 2/4 [prettytable]
   ---------------------------------------- 4/4 [ipython-sql]

Successfully installed ipython-genutils-0.2.0 ipython-sql-0.5.0 prettytable-3.17.0 sqlparse-0.5.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
from dotenv import load_dotenv
import pandas as pd
# загрузка переменных
load_dotenv()

True

### Подключение к PostgreSQL

In [4]:
from sqlalchemy.engine import URL
import os

host = os.getenv("DB_HOST") or 'localhost'  # если переменная не установлена, используем localhost
port = os.getenv("DB_PORT")
db = os.getenv("DB_NAME")
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")

conn = URL.create(
    "postgresql",
    username=user,
    password=password,
    host=host,
    database=db,
    port=port
).render_as_string(hide_password=False)

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

### Техническая функция чтобы удобно было вызывать sql запросы (вариант без sql ячеек)

In [23]:
def execute_sql(string: str, connection_string = conn):
    df = pd.read_sql_query(string, con=connection_string)
    return df

#### Вот как может использоваться

In [24]:
execute_sql(
    "SELECT * "
    "FROM user_logs "
    "LIMIT 10",
)

,courseid,userid,num_week,s_all,s_all_avg,s_course_viewed,s_course_viewed_avg,s_q_attempt_viewed,s_q_attempt_viewed_avg,s_a_course_module_viewed,...,s_a_submission_status_viewed_avg,namer_level,name_vatt,depart,name_osno,name_formopril,leveled,num_sem,kurs,date_vatt
0,71262,34527,6,9,9,4,4,0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022
1,71262,34527,7,0,"4,5",0,2,0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022
2,71262,34527,8,0,3,0,"1,3333",0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022
3,71262,34527,9,0,"2,25",0,1,0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022
4,71262,34527,10,0,"1,8",0,"0,8",0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022
5,71262,34527,11,1,"1,6667",1,"0,8333",0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022
6,71262,34527,12,0,"1,4286",0,"0,7143",0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022
7,71262,34527,13,0,"1,25",0,"0,625",0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022
8,71262,34527,14,0,"1,1111",0,"0,5556",0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022
9,71262,34527,15,1,"1,1",1,"0,6",0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022

### Далее буду использовать sql-ячейки потому-что так удобнее

In [22]:
%%sql
SELECT * FROM user_logs LIMIT 10;

,courseid,userid,num_week,s_all,s_all_avg,s_course_viewed,s_course_viewed_avg,s_q_attempt_viewed,s_q_attempt_viewed_avg,s_a_course_module_viewed,...,s_a_submission_status_viewed_avg,namer_level,name_vatt,depart,name_osno,name_formopril,leveled,num_sem,kurs,date_vatt
0,71262,34527,6,9,9,4,4,0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022
1,71262,34527,7,0,"4,5",0,2,0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022
2,71262,34527,8,0,3,0,"1,3333",0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022
3,71262,34527,9,0,"2,25",0,1,0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022
4,71262,34527,10,0,"1,8",0,"0,8",0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022
5,71262,34527,11,1,"1,6667",1,"0,8333",0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022
6,71262,34527,12,0,"1,4286",0,"0,7143",0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022
7,71262,34527,13,0,"1,25",0,"0,625",0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022
8,71262,34527,14,0,"1,1111",0,"0,5556",0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022
9,71262,34527,15,1,"1,1",1,"0,6",0,0,0,...,0,3,Экзамен,22,1,1,1,2,2,18.06.2022

Вам предоставлена БД с логами (действиями) студентов на образовательном портале за весенний семестр (агрегация по каждой неделе) по отдельному электронному курсу - таблица user_logs (примечание. создана в предыдущих л.р.).
- сourseid — уникальный идентификатор курса, дисциплины;
- userid — уникальный идентификатор студента (не используется в обучении);
- num_week — номер недели в году;
- s_all — количество всех событий на текущий момент;
- s_all_avg — среднее количество всех событий в неделю;
- s_course_viewed — количество просмотров курса;
- s_course_viewed_avg — среднее количество просмотров курса в неделю;
- s_q_attempt_viewed — количество просмотров теста;
- s_q_attempt_viewed_avg — среднее количество просмотров теста в неделю;
- s_a_course_module_viewed — количество просмотров модуля в курсе;
- s_a_course_module_viewed_avg — среднее количество просмотров модуля в курсе в неделю;
- s_a_submission_status_viewed — количество отправленных заданий на проверку;
- s_a_submission_status_viewed_avg — среднее количество ответов;
- namer_level — оценка за дисциплину;
- depart — номер кафедры;
- name_osno — основа обучения (имеет два значения: бюджет или контракт);
- name_formopril — форма обучения;
- leveled — уровень образования (имеет два значения: бакалавриат, магистратура);
- num_sem — номер семестра;
- kurs — номер курса учебной группы.

Также в таблице  departments хранятся названия кафедр, таблица связана с логами по полю depart:
id - код кафедры;
name - сокращенное название кафедры.

## Задание 1 (если до этого еще этот шаг не был выполнен):

Измените данные вещественного типа, сейчас целая и дробная часть разделены запятой, замените ее на точку. 

Выведите первые 10 записей, чтобы проверить результат предобработки.

### Шаг был выполнен в лабораторной работе 7

## Задание 2: 

Выведите количество кафедр, за которыми закреплены курсы на портале.

In [26]:
%%sql
SELECT -- количество уникальных кафедр
    COUNT(DISTINCT depart)
FROM user_logs;

   count
0     43

##  Задание 3:

Выведите сколько у каждой кафедры закреплено электронных курсов на портале. 
Требуется выводит сокращенное название кафедры и количество курсов. 
У какой кафедры больше всего курсов на портале?

In [30]:
%%sql
SELECT departments.name, COUNT(DISTINCT courseid) as course_sum
FROM user_logs
JOIN departments ON departments.id = user_logs.depart
GROUP BY departments.name
ORDER BY course_sum DESC

         name  course_sum
0        ДиСО          53
1        ПОиД          42
2        МиХТ          42
3      ГМиТТК          40
4       ЛиУТС          36
5       БИиИТ          35
6      ГМУиУП          35
7      ПиЭММО          33
8       АЭПиМ          33
9         ЛиП          33
10       ПиСЗ          32
11    Эконом.          32
12        ТОМ          30
13    ГМДиОПИ          29
14       ЛПиМ          28
15       РМПИ          28
16    МиТОДиМ          28
17       ВТиП          25
18    Психол.          23
19         ВИ          22
20       ТССА          21
21    Дизайна          20
22   Менеджм.          20
23        ЯиЛ          20
24         CC          19
25       ПМиИ          19
26       АиИИ          19
27       ТиЭС          19
28      Химии          18
29        ХОМ          18
30    РЯОЯиМК          17
31        ЭПП          16
32       ИиИБ          16
33        АСУ          16
34     Физики          16
35       ЭиМЭ          16
36       УиИС          15
37     СРиППО          14
38     ПЭиБЖД          11
39  Физкульт.           5
40       ЦДОМ           4
41        ИТМ           3
42      УСиБА           2

Как мы можем видеть кафедра ДиСО имеет больше всего курсов

## Задание 4:

Ответьте на вопрос: существуют ли курсы, за которыми закреплено несколько кафедр? Если такие курсы есть, то выведите их количество.
Также выведите названия кафедр, которые совместно преподают один и тот же курс.

In [45]:
%%sql
SELECT COUNT(*) AS multicursi
FROM (
    SELECT courseid
    FROM public.user_logs
    GROUP BY courseid
    HAVING COUNT(DISTINCT depart) > 1
) AS subquery;

   multicursi
0          60

Получаем кафедры которые совместно ведут курсы

In [48]:
%%sql
SELECT
    courseid,
    string_agg(DISTINCT dep.name, ', ')
FROM
    user_logs
JOIN
    departments AS dep ON depart = dep.id
GROUP BY
    courseid
HAVING
    COUNT(DISTINCT depart) > 1;

    courseid                                         string_agg
0      71495                                 ГМиТТК, ПиСЗ, УиИС
1      71508                                         ПиСЗ, УиИС
2      71541                                         ПиСЗ, УиИС
3      71547                                         ПиСЗ, УиИС
4      71549                                       ГМиТТК, ТиЭС
5      71571                                  ЛиУТС, ПиСЗ, УиИС
6      71632                                           CC, ВТиП
7      71736                                      ГМДиОПИ, ЭиМЭ
8      71852                                         АЭПиМ, ЭПП
9      71857                                         АЭПиМ, ЭПП
10     71884                                         АЭПиМ, ЭПП
11     71892                                   АЭПиМ, ТиЭС, ЭПП
12     71904                                         АЭПиМ, ЭПП
13     72126                                        АЭПиМ, УиИС
14     72314                                      Дизайна, ЛПиМ
15     72347                                      Дизайна, ЛПиМ
16     72358                                          МиХТ, ТОМ
17     72359                                    ЛПиМ, МиХТ, ТОМ
18     72380                           ГМДиОПИ, ЛПиМ, МиХТ, ТОМ
19     72392                                    ЛПиМ, МиХТ, ТОМ
20     72402                           ГМДиОПИ, ЛПиМ, МиХТ, ТОМ
21     72416                                    ЛПиМ, МиХТ, ТОМ
22     72447                                    ЛПиМ, МиХТ, ТОМ
23     72457                           ГМДиОПИ, ЛПиМ, МиХТ, ТОМ
24     72460                                    ЛПиМ, МиХТ, ТОМ
25     72462                                          МиХТ, ТОМ
26     72469                                          МиХТ, ТОМ
27     72800                                         АЭПиМ, ХОМ
28     72865                                       Дизайна, ТОМ
29     72885                                  Дизайна, ТОМ, ХОМ
30     73574                                           CC, ДиСО
31     73986                                     БИиИТ, Эконом.
32     75810                              ГМДиОПИ, ГМиТТК, РМПИ
33     75833                       ГМДиОПИ, ГМиТТК, ЛиУТС, РМПИ
34     75834                              ГМДиОПИ, ГМиТТК, РМПИ
35     75839                              ГМДиОПИ, ГМиТТК, РМПИ
36     75849                              ГМДиОПИ, ГМиТТК, РМПИ
37     76293                                      ПиСЗ, Эконом.
38     78057  АСУ, АЭПиМ, ВИ, ВТиП, ГМДиОПИ, ГМиТТК, ГМУиУП,...
39     79426                       ГМДиОПИ, ГМиТТК, ЛиУТС, РМПИ
40     81847                                         АЭПиМ, ЭПП
41     82754                                      ДиСО, Психол.
42     82755                                      ДиСО, Психол.
43     83853                                    ЛПиМ, МиХТ, ТОМ
44     84103                                      ДиСО, Эконом.
45     84140                                     БИиИТ, Эконом.
46     84352                                          ДиСО, ЛиП
47     84834                              ГМДиОПИ, ГМиТТК, РМПИ
48     86712                                      ДиСО, Психол.
49     87097                                          ДиСО, ЛиП
50     87396                              ГМДиОПИ, ГМиТТК, РМПИ
51     87935                                          ТОМ, ЭиМЭ
52     88349                                         АЭПиМ, ЭПП
53     88415                                 ГМДиОПИ, МиХТ, ТОМ
54     88594                                            ВИ, ХОМ
55     88598                                            ВИ, ХОМ
56     88603                                            ВИ, ХОМ
57     88653                                        БИиИТ, ПМиИ
58     88659                                        БИиИТ, ПМиИ
59     88888                                           ЛиП, ЯиЛ

## Задание 5:

Выведите количество студентов, которые получили 2, 3, 4, 5.

Пример вывода:

| namer_level |	count |
|-----|------|
|2 |	4 |
|3 |	3435 |
|4 | 	4676765|
|5 | 232 |

In [1]:
%%sql
SELECT namer_level, count(user_logs.namer_level)
FROM user_logs
GROUP BY namer_level

   namer_level   count
0            2   44184
1            3   70536
2            4  130104
3            5  169704

## Задание 6:

Выведите студента, который больше всех работает на портале (у него максимальное количество логов за вест период обучения).

*на сколько я понял имеется ввиду максимальное число записей с 1 userid*

*нет видимо это просто s_all*

*хотя это может быть и s_all_avg, я не понял...*

In [11]:
%%sql
SELECT userid, SUM(s_all) AS s_all_max
FROM user_logs
GROUP BY userid
ORDER BY s_all_max desc
LIMIT 1

   userid  s_all_max
0   28871      10300

## Задание 7:

Выведите по каждой недели среднее количество всех событий на портале.

In [15]:
%%sql
SELECT user_logs.num_week, AVG(user_logs.s_all)
FROM user_logs
GROUP BY num_week;

    num_week        avg
0          6  13.796607
1          7   9.616142
2          8   8.028543
3          9   9.393296
4         10   8.208546
5         11  10.022001
6         12   9.381716
7         13  10.014011
8         14   9.860178
9         15  10.353694
10        16  10.285433
11        17  10.515806
12        18   9.671376
13        19  11.113478
14        20  14.447198
15        21  18.503821
16        22  22.487321
17        23  22.261522
18        24  23.012101
19        25  18.216362
20        26   8.602941
21        27   1.252953
22        28   0.089972
23        29   0.054713

## Задание 8: 

Выведите название кафедры, у которой больше всего отличников.

Отдельно выведите название кафедры, у которой больше всего двоечников.

In [8]:
%%sql
SELECT count(DISTINCT userid) AS otlishniki, departments.name
FROM user_logs
JOIN departments ON departments.id = user_logs.depart
WHERE namer_level = 5
GROUP BY departments.name
ORDER BY otlishniki DESC
LIMIT 1

   otlishniki  name
0         310  ДиСО

In [10]:
%%sql
SELECT count(DISTINCT userid) AS dvoechnkiki, departments.name
FROM user_logs
JOIN departments ON departments.id = user_logs.depart
WHERE namer_level = 2
GROUP BY departments.name
ORDER BY dvoechnkiki DESC
LIMIT 1

   dvoechnkiki     name
0           72  Эконом.

    ## Задание 9:
Провести анализ пиковой активности студентов перед экзаменом (с использованием (Common Table Expression — CTE), оператор with).

Вывести, на какой неделе семестра студенты проявляли наибольшую активность в курсе в целом, и как эта активность распределяется между студентами-бюджетниками и контрактниками.

Пример вывода :

| name_osno | week_number	| avg_s_all	| avg_s_course_viewed |	avg_s_q_attempt_viewed |
|-----|------|------|------|------|
| бюджет |	14	| 125.45 |	45.67 |	32.12 |
|контракт |	14	| 98.76 |	38.90 |	25.43 |

In [13]:
%%sql
WITH week_activity AS (
    -- Средняя активность по неделям
    SELECT
        CASE
            WHEN name_osno = 1 THEN 'бюджет'
            WHEN name_osno = 2 THEN 'контракт'
            ELSE 'не указано'
        END AS name_osno,
        num_week,
        AVG(s_all) AS avg_as_all,
        AVG(s_course_viewed) AS avg_s_course_viewed,
        AVG(s_q_attempt_viewed) AS s_q_attempt_viewed_avg
    FROM user_logs
    GROUP BY name_osno, num_week
),
week AS (
    -- Находим неделю, где s_all_avg был самым высоки
    SELECT num_week
    FROM user_logs
    GROUP BY num_week
    ORDER BY AVG(s_all) DESC
    LIMIT 1
)
-- данные пиковой недели
SELECT * FROM week_activity
WHERE num_week = (SELECT num_week FROM week)
ORDER BY name_osno;

  name_osno  num_week  avg_as_all  avg_s_course_viewed  s_q_attempt_viewed_avg
0    бюджет        24   20.786572             3.782462                4.941646
1  контракт        24   28.687770             4.734430                5.418294